values:
- groupName: Connectivity
  properties:
  - id: Internet
    title: Internet Type
    type: categorical
  - id: WLAN_Standard
    title: WiFi Standard
    type: categorical
  - id: Mesh
    title: Mesh Support
    type: boolean
- groupName: Features & Power
  properties:
  - id: NAS_Funktion
    title: NAS Function
    type: boolean
  - id: Stromverbrauch_W
    sliderOptions:
      direction: less
    title: Power (W)
    type: continuous-single
- groupName: Firmware
  properties:
  - id: Aktuelle_Firmware_Version
    sliderOptions:
      direction: greater
    title: Firmware Version (min.)
    type: stepped-continuous-single
